kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: demo-plugin
spec:
 plugin:
    cncftaeplugin:
      HeaderName: "X-Traefik-Test"
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/who`)
    kind: Rule
    services:
    - name: whoami
      port: 80
    middlewares:
    - name: demo-plugin
